simplemooc/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *


urlpatterns = [
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('sair/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('cadastrar/', register, name='register'),
    path('', dashboard, name='dashboard'),
    path('editar-senha/', edit_password, name='edit_password'),
    path('editar-usuario/', edit_user, name='edit_user'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('simplemooc.core.urls', 'core'), namespace='core')),
    path('conta/', include(('simplemooc.accounts.urls', 'accounts'), namespace='accounts')),
    path('cursos/', include(('simplemooc.courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nome de Usuário', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
            'O nome de usuário só pode conter letras, digitos ou os '
            'seguintes caracteres: @/./+/-/_', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        related_name='resets', on_delete=models.CASCADE
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name_plural = 'Novas Senhas'
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#cria-se uma instância do UserCreationForm

class RegisterForm(UserCreationForm):
    #não existe este campo, portanto está sendo criado por aqui e acrescentando aos que já existem
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            #se existir exibe um erro
            raise forms.ValidationError('Já existe usuário com este E-mail')
        else:
            #se não existir retorna o email
            return email
    #cria-se um novo save que vai substituir o save do UserCreationForm, colocando o email e salvando.
    def save(self):

        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.save()
        return user


class EditAccountForm(forms.ModelForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = User.objects.filter(
            email=email).exclude(pk=self.instance.pk)
        if queryset.exists():
            raise forms.ValidationError('Já existe usuário com este E-mail')
        else:
            return email

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

simplemooc/accounts/views.py
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required



from .forms import RegisterForm, EditAccountForm

# Create your views here.
from ..courses.models import Course


@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    # courses = Course.objects.all()
    # context = {
    #     'courses': courses
    # }
    return render(request, template_name)


def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        #cria um formulário passando os dados da requisição
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            #chama o login url que está no settings
            return redirect(settings.LOGIN_URL)
    else:
        #cria um formulário vazio
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

@login_required
def edit_user(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)



@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading">Meus Cursos</a>
            <ul>
                <li><a href="#">Curso 1</a></li>
                <li><a href="#">Curso 2</a></li>
                <li class="pure-menu-heading">Minha Conta</li>
                <li><a href="{% url 'accounts:edit_user' %}">Editar Conta</a></li>
                <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <p><strong>Usuário</strong>: {{ user }}</p>
            <p><strong>E-mail</strong>: {{ user.email }}</p>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_user' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterados com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Salvar Modificações</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon" align="center">
    <div class="pure-u-1" align="center">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
              {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group" >
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors}}
                </div>
                {% endfor %}
                <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Entrar </button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a><br>
                Esqueceu a senha? <a href="{% url 'accounts:edit_password' %}" title="">Alterar senha</a><br>
            </p>
        </form>
    </div>
</div>

{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon" align="center">
    <div class="pure-u-1" align="center">
        {% if success %}
        <p>Sua senha foi criada com sucesso</p>
        {% else %}
        <h2>Informe sua nova Senha</h2>
        <form class="pure-form pure-form-stacked" method="post">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

simplemooc/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon" align="center">
    <div class="pure-u-1" align="center">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
              {{ form.non_field_errors }}
              {% for field in form %}
                <div class="pure-control-group" >
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors}}
                </div>
                {% endfor %}
                <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}